/**
 * Barrel do schema. É o que `drizzle.config.ts` lê para gerar migrations —
 * toda tabela nova precisa ser reexportada aqui.
 */
export * from './enums'
export * from './numeracao'
export * from './autoatendimento'
export * from './acesso'
export * from './pacientes'
export * from './referencia'
export * from './convenios'
export * from './agenda'
export * from './clinico'
export * from './periodontal'
export * from './laboratorio'
export * from './esterilizacao'
export * from './tratamento'
export * from './financeiro'
export * from './despesas'
export * from './recebimento'
export * from './tiss'
export * from './estoque'
export * from './documentos'
export * from './mensageria'
export * from './relacionamento'
export * from './auditoria'
export * from './assinatura'
